# Generated by Django 4.0.4 on 2022-05-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photo_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photos.category'),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.location'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.TextField(),
        ),
    ]
