# Generated by Django 4.0.4 on 2022-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photos_image_photos_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
