# Generated by Django 4.0.4 on 2022-05-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image',
        ),
    ]
