# Generated by Django 4.0.4 on 2022-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_remove_photos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(default='No image', upload_to='pictures/'),
        ),
    ]
